In [1]:
import pandas
from datetime import datetime
from pytz import utc
data = pandas.read_csv("reviews.csv" , parse_dates = ['Timestamp'])
data['Rating']

0        4.0
1        4.0
2        4.0
3        5.0
4        4.5
        ...
44995    4.0
44996    5.0
44997    5.0
44998    5.0
44999    5.0
Name: Rating, Length: 45000, dtype: float64

In [2]:
#Timebased filtering
data[(data['Timestamp'] >= datetime(2020,7,1,tzinfo=utc)) & (data['Timestamp'] <= datetime(2020,12,31,tzinfo=utc))]

,Course Name,Timestamp,Rating,Comment
3065,Interactive Data Visualization with Python and...,2020-12-30 23:28:34+00:00,3.0,NaN
3066,The Python Mega Course: Build 10 Real World Ap...,2020-12-30 22:59:02+00:00,4.0,NaN
3067,The Python Mega Course: Build 10 Real World Ap...,2020-12-30 22:40:10+00:00,4.5,NaN
3068,The Python Mega Course: Build 10 Real World Ap...,2020-12-30 21:56:41+00:00,4.5,NaN
3069,The Python Mega Course: Build 10 Real World Ap...,2020-12-30 21:14:34+00:00,4.5,NaN
...,...,...,...,...
9729,The Python Mega Course: Build 10 Real World Ap...,2020-07-01 03:09:44+00:00,3.5,NaN
9730,The Python Mega Course: Build 10 Real World Ap...,2020-07-01 03:09:12+00:00,5.0,NaN
9731,The Python Mega Course: Build 10 Real World Ap...,2020-07-01 02:40:58+00:00,4.0,NaN
9732,The Python Mega Course: Build 10 Real World Ap...,2020-07-01 02:04:02+00:00,5.0,nice
9733,The Python Mega Course: Build 10 Real World Ap...,2020-07-01 00:01:34+00:00,2.0,Hard to follow if u have no experience program...